const slug=new URLSearchParams(location.search).get('produto');
const product=products.find(p=>p.slug===slug);
const root=document.querySelector('#produto');
if(!product){root.innerHTML='<h1>Peça não encontrada.</h1><a class="pill outline" href="./index.html#colecao">Voltar à coleção</a>';}else{
 document.title=product.type+' '+product.name+' — Clami';
 root.innerHTML=`<nav class="breadcrumb" aria-label="Você está aqui"><a href="./index.html#colecao">Coleção</a><span>/</span><span>${product.type} ${product.name}</span></nav><div class="product-detail-layout"><div><div class="product-view-tabs" role="tablist" aria-label="Visualização do produto"><button role="tab" id="tab-photo" aria-controls="panel-photo" aria-selected="true">Fotografia</button><button role="tab" id="tab-ar" aria-controls="panel-ar" aria-selected="false" tabindex="-1">No seu ambiente <small>Em breve</small></button></div><div id="panel-photo" role="tabpanel" aria-labelledby="tab-photo"><img class="product-detail-photo" src="./assets/${product.detailImage || product.image}" alt="${product.type} ${product.name}"></div><div id="panel-ar" class="ar-preview" role="tabpanel" aria-labelledby="tab-ar" hidden><div class="ar-room" aria-hidden="true"><span>AR</span></div><p class="eyebrow">Realidade aumentada · Em breve</p><h2>Veja na sua casa.</h2><p>Visualize esta peça em casa pela câmera do celular. Em breve.</p><button class="pill outline" disabled>Ver no meu ambiente</button></div></div><div class="product-detail-copy"><p class="eyebrow">${product.type}</p><h1>${product.name}</h1><p class="designer">${product.designer}</p>${product.description.startsWith(product.type+' '+product.name+'. Consulte')?'':`<p>${product.description}</p>`}<div class="product-actions"><a class="pill dark" href="${contactUrl(product.type+' '+product.name)}" target="_blank" rel="noopener">Solicitar informações</a></div><p class="model-note">Acabamentos, medidas e disponibilidade sob consulta.</p><a class="text-link" href="./index.html#lojas">Conheça nossas lojas</a></div></div>`;
 const tabs=[...document.querySelectorAll('[role="tab"]')];
 function selectTab(tab){tabs.forEach(b=>{const selected=b===tab;b.setAttribute('aria-selected',selected);b.tabIndex=selected?0:-1;document.getElementById(b.getAttribute('aria-controls')).hidden=!selected;});}
 tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>selectTab(tab));tab.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=tabs[e.key==='Home'?0:e.key==='End'?1:1-i];selectTab(next);next.focus();}});});
}
